using System.Collections.Generic;

namespace AiGame.Systems;

public enum GameLanguage
{
    Chinese,
    English,
}

public static class Loc
{
    private static readonly Dictionary<string, string> Zh = new()
    {
        ["ui.header.state"] = "前线补给中",
        ["ui.header.mode"] = "打造装备、补给勇士、击退来袭敌人。每 30 秒自动保存。",
        ["ui.header.clock"] = "战备 {0}",
        ["ui.header.lang"] = "EN",
        ["ui.header.resources"] = "金币 {0}    熔火 {1}    名望 {2}    战备 +{3}%",

        ["ui.hero.title"] = "主视觉舞台",
        ["ui.hero.desc"] = "制造带属性的武器、防具和饰品，及时分配给前线勇士，帮助他们击败一波波敌人。",
        ["ui.hero.goal"] = "今晚目标",
        ["ui.hero.goalValue"] = "稳定前线战斗节奏",
        ["ui.hero.path"] = "推荐方向",
        ["ui.hero.pathValue"] = "武器输出 / 护甲续航 / 饰品触发",
        ["ui.hero.growth"] = "成长节奏",
        ["ui.hero.growthValue"] = "更强装备、词缀与战斗节奏",
        ["ui.hero.stage"] = "锻造舞台",
        ["ui.hero.noBuff"] = "",
        ["ui.hero.stats"] = "攻 {0} / 防 {1} / 血 {2} / 速 {3:0.0}s",
        ["ui.hero.hp"] = "生命",
        ["ui.hero.emptySlot"] = "空",
        ["ui.hero.enemy"] = "{0}  攻{1} 防{2}",
        ["ui.hero.lane"] = "战线 {0}",
        ["ui.hero.enemyHp"] = "敌血",
        ["ui.hero.cast"] = "攻击 {0:0.0}s",
        ["ui.hero.waitGear"] = "三槽齐后开战",
        ["ui.hero.waitGearSlots"] = "需要 {0} 件装备",
        ["ui.hero.needSlots"] = "需求：{0}",
        ["ui.hero.noActiveBuff"] = "暂无装备增益",
        ["ui.hero.activeBuffs"] = "增益：{0}",

        ["ui.customer.title"] = "前线战斗",
        ["ui.customer.desc"] = "每条战线由一名勇士迎战一名敌人。凑齐武器、防具、饰品后才会开战；胜负都会换上新一组战斗。",
        ["ui.customer.need"] = "战备需求：{0}",
        ["ui.customer.patience"] = "生命",
        ["ui.customer.selected"] = "已关注 {0}",
        ["ui.customer.slot"] = "装备槽位",
        ["ui.customer.needSlot"] = "拖入 {0}",

        ["ui.forge.title"] = "锻造台",
        ["ui.forge.desc"] = "选择要打造的战备装备。陈设会提升锻造效率与战斗报酬。",
        ["ui.forge.idle"] = "锻造台空闲",
        ["ui.forge.progress"] = "打造中：{0}",

        ["ui.rack.title"] = "战备架",
        ["ui.rack.desc"] = "打造完成的装备会存放在这里。拿起后拖到对应勇士槽位。",
        ["ui.rack.none"] = "还没有成品。先在锻造台打造一件装备。",
        ["ui.rack.tip"] = "拖到勇士的对应槽位",
        ["ui.rack.holding"] = "当前拿起：{0}",
        ["ui.rack.emptyHand"] = "当前未拿起任何成品",
        ["ui.rack.pick"] = "已拿起 {0}",
        ["ui.rack.cancel"] = "放回了手上的成品",
        ["ui.rack.drag"] = "装备：{0}",
        ["ui.rack.dragGear"] = "{0} -> {1}",
        ["ui.rack.slotHeld"] = "该位置已被拖起",

        ["ui.progress.title"] = "战役进度",
        ["ui.progress.save"] = "保存",
        ["ui.progress.reset"] = "删档",
        ["ui.progress.shift"] = "第 {0} 阶战线",
        ["ui.progress.served"] = "已完成补给：{0}",
        ["ui.progress.wave"] = "第 {0} 波敌人",
        ["ui.progress.enemyHp"] = "{0} {1}/{2}",
        ["ui.progress.party"] = "勇士存活：{0}/{1}",
        ["ui.progress.special.none"] = "当前重点：待刷新",
        ["ui.progress.special"] = "重点装备：{0}",
        ["ui.progress.combo"] = "连续击退：{0} / 最高：{1}",
        ["ui.progress.event.wait"] = "战线目标：待触发",
        ["ui.progress.event.pending"] = "新的战斗目标即将出现。",
        ["ui.progress.event.next"] = "再完成 {0} 次补给，触发新的战线目标。",
        ["ui.progress.event.reward"] = "{0} 奖励：+{1} 金币",

        ["ui.shop.title"] = "战备陈设",
        ["ui.shop.desc"] = "陈设不再单纯产钱，而是提升锻造效率与击退敌人的结算报酬。",
        ["ui.owned.title"] = "战备资产",
        ["ui.owned.desc"] = "这里汇总已布置的战备设施，它们会强化核心补给循环。",
        ["ui.owned.decorSection"] = "已购陈设",
        ["ui.owned.buffSection"] = "临时效果",
        ["ui.owned.empty"] = "还没有陈设，先摆上一件工具吧。",
        ["ui.owned.noBuff"] = "暂无临时效果。",
        ["ui.owned.buffUses"] = "剩余 {0} 次补给",

        ["ui.blessing.title"] = "",
        ["ui.blessing.desc"] = "",

        ["ui.button.craft"] = "打造",
        ["ui.button.buy"] = "购入",
        ["ui.button.pick"] = "看单",
        ["ui.button.focus"] = "锁定",
        ["ui.button.deliver"] = "装备",
        ["ui.button.hold"] = "拿起",
        ["ui.button.cancel"] = "放下",
        ["ui.button.choose"] = "选择",
        ["ui.button.discard"] = "丢弃",

        ["ui.product.economy"] = "成本 {0} / 售价 {1} / 利润 {2}",
        ["ui.product.slotStats"] = "{0}  攻+{1} 防+{2} 血+{3}",
        ["ui.product.craftCost"] = "成本 {0} / 追击 {1:0}%",
        ["ui.product.costOnly"] = "成本 {0}",
        ["ui.product.tooltip"] = "{0}\n槽位：{1}\n攻击 +{2}  防御 +{3}  生命 +{4}\n攻击间隔 {5:+0.0;-0.0;0.0}s\n追击 {6:0}%  暴击 {7:0}%  吸血 {8:0}%",
        ["ui.item.noRoll"] = "基础成品",
        ["ui.product.buff"] = "{0} {1:0}s：{2}",
        ["ui.product.slot"] = "槽位",
        ["ui.stat.attack"] = "攻",
        ["ui.stat.defense"] = "防",
        ["ui.stat.vitality"] = "血",
        ["ui.stat.speed"] = "间隔",
        ["ui.stat.chase"] = "追击",
        ["ui.stat.crit"] = "暴击",
        ["ui.stat.leech"] = "吸血",
        ["ui.decor.cost"] = "价格 {0}",
        ["ui.decor.passive"] = "战备强度 +{0}",
        ["ui.decor.service"] = "锻造/报酬效率 +{0}",
        ["ui.decor.effect"] = "锻造 -{0:0.#}% / 战利 +{1:0.#}%",

        ["ui.toast.autosave"] = "已自动保存",
        ["ui.toast.reset"] = "存档已删除，重新开始补给。",
        ["ui.toast.blessing"] = "",
        ["ui.toast.shift"] = "战线提升到第 {0} 阶",
        ["ui.toast.income"] = "+{0} 金币  +{1} 熔火值",

        ["ui.message.start"] = "补给铺开门，前线勇士正在等待装备。",

        ["game.noCoins"] = "金币不够，先完成几次战斗补给。",
        ["game.decorOwned"] = "这个陈设已经拥有了。",
        ["game.buyDecor"] = "布置了 {0}，战备效率提升。",
        ["game.getBlessing"] = "",

        ["game.craft.busy"] = "锻造台已经在忙了。",
        ["game.craft.rackFull"] = "战备架已满，先把现有装备装配出去。",
        ["game.craft.noCoins"] = "金币不足，打造需要 {0}。",
        ["game.craft.start"] = "投入 {1} 金币，开始打造 {0}。",
        ["game.craft.complete"] = "{0} 已打造完成，放上成品架。",
        ["game.craft.discard"] = "丢弃了一件{0}成品，成品架腾出了空间。",

        ["game.delivery.noItem"] = "手上没有可装备的成品。",
        ["game.delivery.noCustomer"] = "没有可以装备的勇士。",
        ["game.delivery.base"] = "{0} 装备了 {1}，获得 +{2}",
        ["game.delivery.requireMatch"] = "这件装备无法放入当前槽位。",
        ["game.delivery.match"] = "，正好满足需求",
        ["game.delivery.miss"] = "，但并不完全对口",
        ["game.delivery.favorite"] = "，而且还是对方偏好的装备",
        ["game.delivery.combo"] = "，连击 x{0}",

        ["game.event.finish"] = "{0} 完成，奖励 +{1} 金币",
        ["game.event.end"] = "{0} 已结束",
        ["game.event.progress"] = "{0} {1}/{2}",
        ["game.event.desc"] = "在接下来的 {0} 次补给内，配置 {1} 件 {2} 装备。",
        ["game.event.melee"] = "前线补刃",
        ["game.event.ranged"] = "远行补给",
        ["game.event.arcane"] = "法师急单",
        ["game.event.defense"] = "守卫加固",
        ["game.event.default"] = "深夜特急军需",

        ["tag.melee"] = "近战",
        ["tag.ranged"] = "远程",
        ["tag.arcane"] = "奥术",
        ["tag.defense"] = "防护",
        ["tag.default"] = "特殊",

        ["content.title"] = "灰炉远征补给店 DEMO",
        ["ui.customer.slotReady"] = "可装备",
        ["ui.customer.slotBlocked"] = "不匹配",
        ["ui.progress.heat"] = "炉火热度 {0}/{1}",
        ["ui.float.gold"] = "+{0} 金币",
        ["ui.float.ember"] = "+{0} 熔火",
        ["ui.float.heat"] = "炉火 +{0}",
        ["ui.float.surge"] = "炉火爆发 +{0} 金币",
        ["ui.float.perfect"] = "完美适配",
        ["ui.float.special"] = "重点装备",
        ["ui.float.ready"] = "打造完成",
        ["ui.float.blessing"] = "",
        ["ui.float.cost"] = "-{0} 金币",
        ["ui.float.damage"] = "-{0} 伤害",
        ["ui.float.slash"] = "刀光",
        ["ui.float.fireball"] = "火球",
        ["ui.float.arrow"] = "箭矢",
        ["ui.float.enemy"] = "反击",
        ["game.delivery.surge"] = "，炉火爆发 +{0} 金币",
        ["game.equip.noHero"] = "没有可以装备的勇士。",
        ["game.equip.wrongSlot"] = "这件装备只能放入 {0} 槽位。",
        ["game.equip.slotNotNeeded"] = "这名勇士当前不需要这个槽位的装备。",
        ["game.equip.done"] = "{0} 装备了 {1}（{2}）。",
        ["game.combat.enemy"] = "{0} 加入战斗，第 {1} 波开始。",
        ["game.combat.hit"] = "勇士造成 {0} 伤害，{1} 受到 {2} 反击伤害。",
        ["game.combat.hitExtra"] = "勇士造成 {0} 伤害，触发 {1} 次追击，{2} 受到 {3} 反击伤害。",
        ["game.combat.victory"] = "击败 {0}，获得 +{1} 金币。",
        ["game.combat.laneHit"] = "{0} 攻击 {1}，造成 {2} 伤害，受到 {3} 反击。",
        ["game.combat.laneHitExtra"] = "{0} 攻击 {1}，造成 {2} 伤害并触发 {3} 次追击，受到 {4} 反击。",
        ["game.combat.laneStrike"] = "{0} 攻击 {1}，造成 {2} 伤害。",
        ["game.combat.laneStrikeExtra"] = "{0} 攻击 {1}，造成 {2} 伤害并触发 {3} 次追击。",
        ["game.combat.enemyHit"] = "{0} 反击 {1}，造成 {2} 伤害。",
        ["game.combat.laneFail"] = "{0} 被 {1} 击退，新的战斗组已抵达。",
        ["game.combat.victoryLane"] = "{0} 击败 {1}，获得 +{2} 金币。结算：{3}。新的战斗组已抵达。",
        ["game.reward.enemy"] = "波次 {0}",
        ["game.reward.hp"] = "剩余生命 {0:0}%",
        ["game.reward.favorite"] = "偏好适配",
        ["game.reward.lean"] = "轻装需求 +{0}",
        ["game.reward.buff"] = "增益 {0}",
        ["game.combat.recover"] = "勇士们撤回重整，损失少量金币。",
        ["enemy.raider"] = "荒野掠夺者",
        ["enemy.wolf"] = "霜牙狼群",
        ["enemy.ogre"] = "铁皮食人魔",
        ["enemy.warlock"] = "裂隙术士",
        ["enemy.drake"] = "灰烬幼龙",
        ["enemy.skeleton"] = "骸骨军团",
        ["enemy.troll"] = "沼地巨魔",
        ["enemy.assassin"] = "影刃刺客",
        ["enemy.golem"] = "符文魔像",
        ["enemy.lich"] = "寒墓巫妖",
        ["slot.weapon"] = "武器",
        ["slot.armor"] = "护甲",
        ["slot.trinket"] = "饰品",
        ["rarity.common"] = "普通",
        ["rarity.fine"] = "精良",
        ["rarity.rare"] = "稀有",
        ["rarity.epic"] = "史诗",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["ui.header.state"] = "Frontline Open",
        ["ui.header.mode"] = "Forge gear, equip heroes, and hold the line. Autosaves every 30 seconds.",
        ["ui.header.clock"] = "Supply {0}",
        ["ui.header.lang"] = "中文",
        ["ui.header.resources"] = "Gold {0}    Ember {1}    Renown {2}    Readiness +{3}%",

        ["ui.hero.title"] = "Forge Overview",
        ["ui.hero.desc"] = "Craft stat-driven weapons, armor, and trinkets, then equip frontline heroes so they can defeat each enemy wave.",
        ["ui.hero.goal"] = "Tonight's Goal",
        ["ui.hero.goalValue"] = "Stabilize the frontline tempo",
        ["ui.hero.path"] = "Suggested Route",
        ["ui.hero.pathValue"] = "Weapon DPS / Armor sustain / Trinket procs",
        ["ui.hero.growth"] = "Growth",
        ["ui.hero.growthValue"] = "Stronger gear, affixes, and combat tempo",
        ["ui.hero.stage"] = "Forge Stage",
        ["ui.hero.noBuff"] = "",
        ["ui.hero.stats"] = "ATK {0} / ARM {1} / HP {2} / SPD {3:0.0}s",
        ["ui.hero.hp"] = "HP",
        ["ui.hero.emptySlot"] = "Empty",
        ["ui.hero.enemy"] = "{0}  ATK {1} ARM {2}",
        ["ui.hero.lane"] = "Lane {0}",
        ["ui.hero.enemyHp"] = "Enemy",
        ["ui.hero.cast"] = "Attack {0:0.0}s",
        ["ui.hero.waitGear"] = "Needs 3 gear slots",
        ["ui.hero.waitGearSlots"] = "Needs {0} item(s)",
        ["ui.hero.needSlots"] = "Needs: {0}",
        ["ui.hero.noActiveBuff"] = "No gear buffs",
        ["ui.hero.activeBuffs"] = "Buffs: {0}",

        ["ui.customer.title"] = "Frontline Battles",
        ["ui.customer.desc"] = "Each lane pairs one hero with one enemy. A lane starts only after weapon, armor, and trinket are equipped; win or lose, a new battle group arrives.",
        ["ui.customer.need"] = "Supply Need: {0}",
        ["ui.customer.patience"] = "HP",
        ["ui.customer.selected"] = "{0} is now highlighted",
        ["ui.customer.slot"] = "Gear Slot",
        ["ui.customer.needSlot"] = "Drop {0} here",
        ["ui.customer.slotReady"] = "Matched",
        ["ui.customer.slotBlocked"] = "Mismatch",

        ["ui.forge.title"] = "Forge",
        ["ui.forge.desc"] = "Choose battlefield gear to forge. Fixtures improve forging speed and combat payouts.",
        ["ui.forge.idle"] = "Forge is idle",
        ["ui.forge.progress"] = "Crafting: {0}",

        ["ui.rack.title"] = "Supply Rack",
        ["ui.rack.desc"] = "Finished gear waits here. Pick it up, then drag it to the matching hero slot.",
        ["ui.rack.none"] = "No finished gear yet. Craft something first.",
        ["ui.rack.tip"] = "Drag to the matching gear slot",
        ["ui.rack.holding"] = "Holding: {0}",
        ["ui.rack.emptyHand"] = "Not holding any finished gear",
        ["ui.rack.pick"] = "Picked up {0}",
        ["ui.rack.cancel"] = "Put the item back down",
        ["ui.rack.drag"] = "Equip: {0}",
        ["ui.rack.dragGear"] = "{0} -> {1}",
        ["ui.rack.slotHeld"] = "Item lifted from this slot",

        ["ui.progress.title"] = "Campaign Progress",
        ["ui.progress.save"] = "Save",
        ["ui.progress.reset"] = "Reset",
        ["ui.progress.shift"] = "Frontline Tier {0}",
        ["ui.progress.served"] = "Supplies fitted: {0}",
        ["ui.progress.wave"] = "Enemy Wave {0}",
        ["ui.progress.enemyHp"] = "{0} {1}/{2}",
        ["ui.progress.party"] = "Heroes alive: {0}/{1}",
        ["ui.progress.special.none"] = "Priority Gear: pending",
        ["ui.progress.special"] = "Priority Gear: {0}",
        ["ui.progress.combo"] = "Defeat streak: {0} / Best: {1}",
        ["ui.progress.heat"] = "Forge Heat {0}/{1}",
        ["ui.progress.event.wait"] = "Frontline Objective: waiting",
        ["ui.progress.event.pending"] = "A new combat objective is coming.",
        ["ui.progress.event.next"] = "Fit {0} more pieces of gear to trigger the next frontline objective.",
        ["ui.progress.event.reward"] = "{0} Reward: +{1} gold",

        ["ui.shop.title"] = "Readiness Fixtures",
        ["ui.shop.desc"] = "Fixtures no longer print idle gold; they improve forge efficiency and combat rewards.",
        ["ui.owned.title"] = "Readiness Assets",
        ["ui.owned.desc"] = "A summary of installed readiness tools that strengthen the core supply loop.",
        ["ui.owned.decorSection"] = "Owned Fixtures",
        ["ui.owned.buffSection"] = "Temporary Effects",
        ["ui.owned.empty"] = "No fixtures yet. Buy a tool or display first.",
        ["ui.owned.noBuff"] = "No temporary effects.",
        ["ui.owned.buffUses"] = "{0} supplies left",

        ["ui.blessing.title"] = "",
        ["ui.blessing.desc"] = "",

        ["ui.button.craft"] = "Craft",
        ["ui.button.buy"] = "Buy",
        ["ui.button.pick"] = "Peek",
        ["ui.button.focus"] = "Focus",
        ["ui.button.deliver"] = "Equip",
        ["ui.button.hold"] = "Hold",
        ["ui.button.cancel"] = "Drop",
        ["ui.button.choose"] = "Choose",
        ["ui.button.discard"] = "Discard",

        ["ui.product.economy"] = "Cost {0} / Price {1} / Profit {2}",
        ["ui.product.slotStats"] = "{0}  ATK+{1} ARM+{2} HP+{3}",
        ["ui.product.craftCost"] = "Cost {0} / Chase {1:0}%",
        ["ui.product.costOnly"] = "Cost {0}",
        ["ui.product.tooltip"] = "{0}\nSlot: {1}\nATK +{2}  ARM +{3}  HP +{4}\nAttack interval {5:+0.0;-0.0;0.0}s\nChase {6:0}%  Crit {7:0}%  Leech {8:0}%",
        ["ui.item.noRoll"] = "Base craft",
        ["ui.product.buff"] = "{0} {1:0}s: {2}",
        ["ui.product.slot"] = "Slot",
        ["ui.stat.attack"] = "ATK",
        ["ui.stat.defense"] = "ARM",
        ["ui.stat.vitality"] = "HP",
        ["ui.stat.speed"] = "Interval",
        ["ui.stat.chase"] = "Chase",
        ["ui.stat.crit"] = "Crit",
        ["ui.stat.leech"] = "Leech",
        ["ui.decor.cost"] = "Cost {0}",
        ["ui.decor.passive"] = "Readiness +{0}",
        ["ui.decor.service"] = "Forge/reward efficiency +{0}",
        ["ui.decor.effect"] = "Forge -{0:0.#}% / Loot +{1:0.#}%",

        ["ui.toast.autosave"] = "Autosaved",
        ["ui.toast.reset"] = "Save deleted. Starting a fresh run.",
        ["ui.toast.blessing"] = "",
        ["ui.toast.shift"] = "Frontline advanced to tier {0}",
        ["ui.toast.income"] = "+{0} gold  +{1} ember",
        ["ui.float.gold"] = "+{0} gold",
        ["ui.float.ember"] = "+{0} ember",
        ["ui.float.heat"] = "Forge heat +{0}",
        ["ui.float.surge"] = "Forge surge +{0} gold",
        ["ui.float.perfect"] = "Perfect fit",
        ["ui.float.special"] = "Featured item",
        ["ui.float.ready"] = "Craft complete",
        ["ui.float.blessing"] = "",
        ["ui.float.cost"] = "-{0} gold",
        ["ui.float.damage"] = "-{0} damage",
        ["ui.float.slash"] = "Slash",
        ["ui.float.fireball"] = "Fireball",
        ["ui.float.arrow"] = "Arrow",
        ["ui.float.enemy"] = "Counter",

        ["ui.message.start"] = "The outfitter is open. Frontline heroes are waiting for gear.",

        ["game.noCoins"] = "Not enough gold. Complete a few more frontline supplies first.",
        ["game.decorOwned"] = "You already own this fixture.",
        ["game.buyDecor"] = "Installed {0}. Readiness improved.",
        ["game.getBlessing"] = "",

        ["game.craft.busy"] = "The forge is already busy.",
        ["game.craft.rackFull"] = "The supply rack is full. Equip something first.",
        ["game.craft.noCoins"] = "Not enough gold. Crafting costs {0}.",
        ["game.craft.start"] = "Spent {1} gold to craft {0}.",
        ["game.craft.complete"] = "{0} is complete and waiting on the rack.",
        ["game.craft.discard"] = "Discarded a {0} item and freed rack space.",

        ["game.delivery.noItem"] = "You are not holding any gear.",
        ["game.delivery.noCustomer"] = "There is no hero to equip.",
        ["game.delivery.base"] = "{0} equipped {1}. Earned +{2}",
        ["game.delivery.requireMatch"] = "That gear cannot fit this slot.",
        ["game.delivery.match"] = ", matching the request",
        ["game.delivery.miss"] = ", but it was not the cleanest fit",
        ["game.delivery.favorite"] = ", and it was their favorite",
        ["game.delivery.combo"] = ", combo x{0}",
        ["game.delivery.surge"] = ", forge surge +{0} gold",
        ["game.equip.noHero"] = "There is no hero to equip.",
        ["game.equip.wrongSlot"] = "This item only fits the {0} slot.",
        ["game.equip.slotNotNeeded"] = "This hero does not need that slot right now.",
        ["game.equip.done"] = "{0} equipped {1} ({2}).",
        ["game.combat.enemy"] = "{0} joins the fight. Wave {1} begins.",
        ["game.combat.hit"] = "Heroes dealt {0} damage. {1} took {2} counter damage.",
        ["game.combat.hitExtra"] = "Heroes dealt {0} damage and triggered {1} chase hits. {2} took {3} counter damage.",
        ["game.combat.victory"] = "Defeated {0}. Earned +{1} gold.",
        ["game.combat.laneHit"] = "{0} hit {1} for {2} damage and took {3} back.",
        ["game.combat.laneHitExtra"] = "{0} hit {1} for {2} damage, triggered {3} chase hit(s), and took {4} back.",
        ["game.combat.laneStrike"] = "{0} hit {1} for {2} damage.",
        ["game.combat.laneStrikeExtra"] = "{0} hit {1} for {2} damage and triggered {3} chase hit(s).",
        ["game.combat.enemyHit"] = "{0} struck {1} for {2} damage.",
        ["game.combat.laneFail"] = "{0} was forced back by {1}. A new battle group arrived.",
        ["game.combat.victoryLane"] = "{0} defeated {1}. Earned +{2} gold. Settlement: {3}. A new battle group arrived.",
        ["game.reward.enemy"] = "wave {0}",
        ["game.reward.hp"] = "HP left {0:0}%",
        ["game.reward.favorite"] = "favorite fit",
        ["game.reward.lean"] = "lean need +{0}",
        ["game.reward.buff"] = "buffs {0}",
        ["game.combat.recover"] = "The heroes pulled back to recover, losing a little gold.",

        ["game.event.finish"] = "{0} complete, reward +{1} gold",
        ["game.event.end"] = "{0} ended",
        ["game.event.progress"] = "{0} {1}/{2}",
        ["game.event.desc"] = "Fit {1} {2} items within the next {0} supplies.",
        ["game.event.melee"] = "Frontline Resharpen",
        ["game.event.ranged"] = "Long Road Supply",
        ["game.event.arcane"] = "Mage Rush",
        ["game.event.defense"] = "Shield Wall Refit",
        ["game.event.default"] = "Midnight Supply Rush",

        ["tag.melee"] = "Melee",
        ["tag.ranged"] = "Ranged",
        ["tag.arcane"] = "Arcane",
        ["tag.defense"] = "Defense",
        ["tag.default"] = "Special",

        ["content.title"] = "Ashforge Expedition Outfitter DEMO",
        ["enemy.raider"] = "Wasteland Raider",
        ["enemy.wolf"] = "Frostfang Pack",
        ["enemy.ogre"] = "Ironhide Ogre",
        ["enemy.warlock"] = "Rift Warlock",
        ["enemy.drake"] = "Ash Drake",
        ["enemy.skeleton"] = "Bone Legion",
        ["enemy.troll"] = "Bog Troll",
        ["enemy.assassin"] = "Shade Assassin",
        ["enemy.golem"] = "Rune Golem",
        ["enemy.lich"] = "Frostgrave Lich",
        ["slot.weapon"] = "Weapon",
        ["slot.armor"] = "Armor",
        ["slot.trinket"] = "Trinket",
        ["rarity.common"] = "Common",
        ["rarity.fine"] = "Fine",
        ["rarity.rare"] = "Rare",
        ["rarity.epic"] = "Epic",
    };

    public static GameLanguage Current { get; private set; } = GameLanguage.Chinese;
    public static string Code => Current == GameLanguage.Chinese ? "zh-CN" : "en";

    public static void Set(string? code)
    {
        Current = code != null && code.StartsWith("en") ? GameLanguage.English : GameLanguage.Chinese;
    }

    public static void Toggle()
    {
        Current = Current == GameLanguage.Chinese ? GameLanguage.English : GameLanguage.Chinese;
    }

    public static string Text(string key, string fallback = "")
    {
        var dict = Current == GameLanguage.Chinese ? Zh : En;
        if (dict.TryGetValue(key, out var value))
        {
            return value;
        }

        return En.TryGetValue(key, out var englishValue) ? englishValue : fallback;
    }

    public static string Format(string key, params object[] args)
    {
        return string.Format(Text(key, key), args);
    }

    public static string Content(string type, string id, string field, string fallback)
    {
        return Text($"{type}.{id}.{field}", fallback);
    }
}
