using System.Collections.Generic;

namespace AiGame.Systems;

public enum GameLanguage
{
    Chinese,
    English,
}

public static class Loc
{
    private static readonly Dictionary<string, string> Zh = new()
    {
        ["ui.header.state"] = "深夜营业中",
        ["ui.header.mode"] = "普通单机经营模式，每 30 秒自动保存。",
        ["ui.header.clock"] = "营业中 {0}",
        ["ui.header.lang"] = "EN",
        ["ui.header.pad"] = "支持键鼠 / 手柄导航",
        ["ui.hero.title"] = "主视觉舞台",
        ["ui.hero.desc"] = "围绕招牌、连击、夜间订单和祝福构筑，把今晚的茶馆节奏跑起来。",
        ["ui.hero.goal"] = "经营目标",
        ["ui.hero.goalValue"] = "做出高价值轮转",
        ["ui.hero.path"] = "推荐思路",
        ["ui.hero.pathValue"] = "招牌 / 连击 / 订单",
        ["ui.hero.growth"] = "养成节奏",
        ["ui.hero.growthValue"] = "解锁新饮品与祝福",
        ["ui.hero.stage"] = "店铺背景",
        ["ui.hero.clerk"] = "店员形象",
        ["ui.hero.clerkDesc"] = "店员会随着你的经营节奏，把夜晚的气氛撑起来。",
        ["ui.customer.title"] = "当前客人",
        ["ui.customer.waitName"] = "暂无客人",
        ["ui.customer.waitLine"] = "下一位客人正在路上。",
        ["ui.products.title"] = "饮品操作台",
        ["ui.products.desc"] = "优先兼顾招牌、连击和当前订单，让出杯顺序也成为策略。",
        ["ui.progress.title"] = "夜班进度",
        ["ui.progress.save"] = "保存",
        ["ui.progress.shift"] = "第 {0} 阶夜班",
        ["ui.progress.served"] = "已服务客人：{0}",
        ["ui.progress.blessings"] = "已拿祝福：{0}",
        ["ui.progress.special.none"] = "今日招牌：待刷新",
        ["ui.progress.special"] = "今日招牌：{0}",
        ["ui.progress.combo"] = "当前连击：{0}  /  最高：{1}",
        ["ui.progress.event.wait"] = "夜间订单：准备中",
        ["ui.progress.event.pending"] = "新的祝福已经出现，先做一次三选一。",
        ["ui.progress.event.next"] = "再服务 {0} 位客人，将触发新的夜间订单。",
        ["ui.progress.event.reward"] = "{0} 奖励：+{1} 金币",
        ["ui.shop.title"] = "装饰商店",
        ["ui.shop.desc"] = "装饰主打长线收益，适合搭配陈设流或事件流。",
        ["ui.owned.title"] = "已拥有装饰",
        ["ui.owned.desc"] = "这里会汇总你已经买下的收益来源。",
        ["ui.owned.empty"] = "还没有装饰，先买一个小摆件吧。",
        ["ui.blessing.title"] = "夜班祝福",
        ["ui.blessing.desc"] = "从三项构筑里挑一项。你可以偏向招牌、连击、陈设、小费或某种饮品流派。",
        ["ui.button.serve"] = "出杯",
        ["ui.button.buy"] = "购入",
        ["ui.button.pick"] = "选择",
        ["ui.product.price"] = "售价 {0} / 茶香 +{1}",
        ["ui.decor.cost"] = "价格 {0}",
        ["ui.decor.passive"] = "被动收益 +{0}/秒",
        ["ui.toast.autosave"] = "已自动保存",
        ["ui.toast.blessing"] = "新的祝福出现了",
        ["ui.toast.shift"] = "夜班提升到 {0} 阶",
        ["ui.toast.bought"] = "{0} 已购入",
        ["ui.toast.income"] = "+{0} 金币  +{1} 茶香",
        ["ui.message.start"] = "茶馆今晚开始营业。",
        ["game.noCustomer"] = "现在还没有客人。",
        ["game.decorOwned"] = "这个装饰已经拥有了。",
        ["game.noCoins"] = "金币不够，先多卖几杯茶。",
        ["game.buyDecor"] = "购入 {0}，被动收益提升。",
        ["game.blessingOwned"] = "这个祝福已经拿过了。",
        ["game.getBlessing"] = "获得祝福：{0}",
        ["game.sale.base"] = "{0} 点了 {1}，收入 +{2}",
        ["game.sale.special"] = "，招牌加成触发",
        ["game.sale.combo"] = "，连击 x{0}",
        ["game.event.finish"] = "{0} 完成，奖励 +{1} 金币",
        ["game.event.end"] = "{0} 已结束",
        ["game.event.progress"] = "{0} {1}/{2}",
        ["game.event.warm"] = "雨夜加单",
        ["game.event.milk"] = "奶香回头客",
        ["game.event.floral"] = "花香试饮",
        ["game.event.refreshing"] = "清爽提神单",
        ["game.event.default"] = "深夜特别订单",
        ["tag.warm"] = "温热",
        ["tag.milk"] = "奶香",
        ["tag.floral"] = "花香",
        ["tag.refreshing"] = "清爽",
        ["tag.default"] = "特别",
        ["content.title"] = "深夜窗台茶馆 DEMO",
        ["product.black_tea.name"] = "雨夜红茶",
        ["product.oolong.name"] = "柚香乌龙",
        ["product.milk_tea.name"] = "窗灯奶茶",
        ["product.ginger_tea.name"] = "生姜暖茶",
        ["product.osmanthus.name"] = "月见桂花露",
        ["product.peach_brew.name"] = "白桃冷泡",
        ["product.chestnut_latte.name"] = "栗子茶拿铁",
        ["product.night_special.name"] = "深夜拼配",
        ["product.jasmine_sencha.name"] = "茉风煎茶",
        ["product.berry_soda_tea.name"] = "莓果气泡茶",
        ["product.charcoal_latte.name"] = "焙茶炭焙拿铁",
        ["product.plum_tea.name"] = "青梅夜露",
        ["product.rose_milk.name"] = "玫瑰奶霜茶",
        ["product.yuzu_spark.name"] = "柚见星气泡",
        ["product.spiced_chai.name"] = "夜火香料奶茶",
        ["product.midnight_fizz.name"] = "午夜回声特饮",
        ["customer.nurse.name"] = "夜班护士",
        ["customer.nurse.line"] = "今天有点累，来一杯热的吧。",
        ["customer.writer.name"] = "写稿的作者",
        ["customer.writer.line"] = "能让我清醒一点就最好了。",
        ["customer.programmer.name"] = "下班程序员",
        ["customer.programmer.line"] = "今晚就靠这一杯续命。",
        ["customer.traveler.name"] = "雨夜旅人",
        ["customer.traveler.line"] = "这座城很安静，你这盏灯很好看。",
        ["customer.photographer.name"] = "深夜摄影师",
        ["customer.photographer.line"] = "等雨停之前，我想再坐一会儿。",
        ["customer.gamer.name"] = "通宵玩家",
        ["customer.gamer.line"] = "这一局结束前，我需要一杯提神的。",
        ["customer.detective.name"] = "失眠侦探",
        ["customer.detective.line"] = "热一点，今晚还要继续找线索。",
        ["customer.singer.name"] = "驻唱歌手",
        ["customer.singer.line"] = "最后一首歌之前，来一杯今晚最好的。",
        ["customer.barista.name"] = "隔壁咖啡师",
        ["customer.barista.line"] = "今天想偷懒喝点茶，顺便看看你这边的新菜单。",
        ["customer.student.name"] = "赶论文的学生",
        ["customer.student.line"] = "今天得通宵了，来杯有点精神的。",
        ["customer.driver.name"] = "夜班司机",
        ["customer.driver.line"] = "再跑两趟单，先来一杯浓一点的。",
        ["customer.designer.name"] = "自由设计师",
        ["customer.designer.line"] = "我在等灵感，顺便等雨停。",
        ["customer.critic.name"] = "深夜食评人",
        ["customer.critic.line"] = "今晚想试点你们家更精致的东西。",
        ["customer.streamer.name"] = "收播主播",
        ["customer.streamer.line"] = "直播刚结束，嗓子还在发热，来杯亮一点的。",
        ["customer.collector.name"] = "旧物收藏家",
        ["customer.collector.line"] = "你的店越来越有味道了，今晚想配一杯暖的。",
        ["customer.producer.name"] = "唱片制作人",
        ["customer.producer.line"] = "凌晨的声音最适合定稿，给我你们今晚最特别的一杯。",
        ["decor.warm_lamp.name"] = "暖黄台灯",
        ["decor.potted_plant.name"] = "窗边盆栽",
        ["decor.record_player.name"] = "旧唱片机",
        ["decor.curtain.name"] = "雨纹窗帘",
        ["decor.shelf.name"] = "木质茶架",
        ["decor.lamp_banner.name"] = "招牌灯箱",
        ["decor.wall_clock.name"] = "古旧挂钟",
        ["decor.brass_kettle.name"] = "铜壶陈列",
        ["decor.postcard_wall.name"] = "旅人明信片墙",
        ["decor.incense_set.name"] = "香篆摆台",
        ["decor.tea_canister.name"] = "锡制茶叶罐组",
        ["decor.floor_lantern.name"] = "落地纸灯",
        ["decor.ceramic_cups.name"] = "手作茶杯套组",
        ["decor.story_board.name"] = "深夜故事板",
        ["decor.rain_sign.name"] = "雨巷霓虹牌",
        ["decor.vinyl_shelf.name"] = "黑胶展示架",
        ["decor.cat_clock.name"] = "招财猫摆钟",
        ["decor.herb_dryer.name"] = "草本晾架",
        ["decor.greenhouse_corner.name"] = "微型温室角",
        ["decor.hanging_lights.name"] = "串灯天幕",
        ["decor.premium_counter.name"] = "黄铜吧台前台",
        ["decor.skylight.name"] = "星顶天窗",
        ["blessing.golden_spoon.name"] = "金边茶勺",
        ["blessing.fragrant_steam.name"] = "香雾回流",
        ["blessing.warm_counter.name"] = "暖柜余温",
        ["blessing.late_tip.name"] = "夜归小费",
        ["blessing.cash_box.name"] = "零钱盒",
        ["blessing.night_prep.name"] = "备料加速",
        ["blessing.house_special.name"] = "招牌记忆",
        ["blessing.quick_hand.name"] = "熟手节奏",
        ["blessing.warm_blend.name"] = "温热拼配",
        ["blessing.flower_recipe.name"] = "花香配方",
        ["blessing.cream_top.name"] = "奶盖余温",
        ["blessing.cold_brew_note.name"] = "冷泡笔记",
        ["blessing.double_order.name"] = "双份点单",
        ["blessing.word_of_mouth.name"] = "口口相传",
        ["blessing.rush_hour.name"] = "高峰应对",
        ["blessing.story_whisper.name"] = "旧城耳语",
        ["blessing.silver_menu.name"] = "银边菜单",
        ["blessing.second_wind.name"] = "二次开台",
        ["blessing.chain_memory.name"] = "连单记忆",
        ["blessing.tea_ritual.name"] = "闭店仪式",
        ["blessing.spotlight_special.name"] = "今晚招牌秀",
        ["blessing.soft_service.name"] = "柔和招待",
        ["blessing.flower_market.name"] = "花市进货",
        ["blessing.milk_street.name"] = "奶霜街角",
        ["blessing.fresh_route.name"] = "清爽路线",
        ["blessing.warm_hearth.name"] = "炉边火光",
        ["blessing.reputation_echo.name"] = "回响口碑",
        ["blessing.festival_board.name"] = "节庆看板",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["ui.header.state"] = "Open Late",
        ["ui.header.mode"] = "Single-player cafe mode. Autosaves every 30 seconds.",
        ["ui.header.clock"] = "Open {0}",
        ["ui.header.lang"] = "中文",
        ["ui.header.pad"] = "Keyboard, mouse, and gamepad ready",
        ["ui.hero.title"] = "Main Stage",
        ["ui.hero.desc"] = "Build tonight's run around specials, combos, night orders, and blessings.",
        ["ui.hero.goal"] = "Goal",
        ["ui.hero.goalValue"] = "Create high-value rotations",
        ["ui.hero.path"] = "Suggested Build",
        ["ui.hero.pathValue"] = "Special / Combo / Orders",
        ["ui.hero.growth"] = "Growth",
        ["ui.hero.growthValue"] = "Unlock drinks and blessings",
        ["ui.hero.stage"] = "Cafe Backdrop",
        ["ui.hero.clerk"] = "Clerk",
        ["ui.hero.clerkDesc"] = "The clerk's energy rises with the rhythm of your shift.",
        ["ui.customer.title"] = "Current Guest",
        ["ui.customer.waitName"] = "No Guest",
        ["ui.customer.waitLine"] = "The next guest is on the way.",
        ["ui.products.title"] = "Drink Station",
        ["ui.products.desc"] = "Balance specials, combos, and current orders so serving order matters.",
        ["ui.progress.title"] = "Night Shift",
        ["ui.progress.save"] = "Save",
        ["ui.progress.shift"] = "Shift Tier {0}",
        ["ui.progress.served"] = "Guests served: {0}",
        ["ui.progress.blessings"] = "Blessings picked: {0}",
        ["ui.progress.special.none"] = "Today's Special: pending",
        ["ui.progress.special"] = "Today's Special: {0}",
        ["ui.progress.combo"] = "Combo: {0}  /  Best: {1}",
        ["ui.progress.event.wait"] = "Night Order: preparing",
        ["ui.progress.event.pending"] = "A new blessing is ready. Pick one first.",
        ["ui.progress.event.next"] = "Serve {0} more guests to trigger a new night order.",
        ["ui.progress.event.reward"] = "{0} Reward: +{1} coins",
        ["ui.shop.title"] = "Decor Shop",
        ["ui.shop.desc"] = "Decor builds steady income and pairs well with passive or event-focused runs.",
        ["ui.owned.title"] = "Owned Decor",
        ["ui.owned.desc"] = "Your purchased passive income sources are listed here.",
        ["ui.owned.empty"] = "No decor yet. Grab a small piece first.",
        ["ui.blessing.title"] = "Night Blessing",
        ["ui.blessing.desc"] = "Pick one of three build choices. Lean into specials, combos, decor, tips, or a drink archetype.",
        ["ui.button.serve"] = "Serve",
        ["ui.button.buy"] = "Buy",
        ["ui.button.pick"] = "Pick",
        ["ui.product.price"] = "Price {0} / Aroma +{1}",
        ["ui.decor.cost"] = "Cost {0}",
        ["ui.decor.passive"] = "Passive +{0}/s",
        ["ui.toast.autosave"] = "Autosaved",
        ["ui.toast.blessing"] = "A new blessing appeared",
        ["ui.toast.shift"] = "Shift advanced to tier {0}",
        ["ui.toast.bought"] = "{0} purchased",
        ["ui.toast.income"] = "+{0} coins  +{1} aroma",
        ["ui.message.start"] = "The tea house is open for the night.",
        ["game.noCustomer"] = "There is no guest right now.",
        ["game.decorOwned"] = "You already own this decor.",
        ["game.noCoins"] = "Not enough coins yet. Sell a few more drinks first.",
        ["game.buyDecor"] = "Bought {0}. Passive income improved.",
        ["game.blessingOwned"] = "You already picked this blessing.",
        ["game.getBlessing"] = "Blessing gained: {0}",
        ["game.sale.base"] = "{0} ordered {1}. Earned +{2}",
        ["game.sale.special"] = ", special bonus applied",
        ["game.sale.combo"] = ", combo x{0}",
        ["game.event.finish"] = "{0} complete, reward +{1} coins",
        ["game.event.end"] = "{0} ended",
        ["game.event.progress"] = "{0} {1}/{2}",
        ["game.event.warm"] = "Rainy Rush",
        ["game.event.milk"] = "Creamy Returners",
        ["game.event.floral"] = "Floral Tasting",
        ["game.event.refreshing"] = "Fresh Pick-Up",
        ["game.event.default"] = "Late Night Order",
        ["tag.warm"] = "Warm",
        ["tag.milk"] = "Milky",
        ["tag.floral"] = "Floral",
        ["tag.refreshing"] = "Fresh",
        ["tag.default"] = "Special",
        ["content.title"] = "Midnight Window Tea House DEMO",
        ["product.black_tea.name"] = "Rainy Night Black Tea",
        ["product.oolong.name"] = "Citrus Oolong",
        ["product.milk_tea.name"] = "Windowlight Milk Tea",
        ["product.ginger_tea.name"] = "Ginger Warm Tea",
        ["product.osmanthus.name"] = "Moon Osmanthus",
        ["product.peach_brew.name"] = "White Peach Cold Brew",
        ["product.chestnut_latte.name"] = "Chestnut Tea Latte",
        ["product.night_special.name"] = "Midnight Blend",
        ["product.jasmine_sencha.name"] = "Jasmine Sencha",
        ["product.berry_soda_tea.name"] = "Berry Spark Tea",
        ["product.charcoal_latte.name"] = "Roasted Charcoal Latte",
        ["product.plum_tea.name"] = "Night Plum Dew",
        ["product.rose_milk.name"] = "Rose Cream Tea",
        ["product.yuzu_spark.name"] = "Yuzu Spark",
        ["product.spiced_chai.name"] = "Midnight Spiced Chai",
        ["product.midnight_fizz.name"] = "Midnight Echo Fizz",
        ["customer.nurse.name"] = "Night Nurse",
        ["customer.nurse.line"] = "Long shift tonight. Something warm, please.",
        ["customer.writer.name"] = "Late Writer",
        ["customer.writer.line"] = "Anything that helps me stay sharp will do.",
        ["customer.programmer.name"] = "After-Hours Coder",
        ["customer.programmer.line"] = "This cup is carrying the whole night.",
        ["customer.traveler.name"] = "Rainy Traveler",
        ["customer.traveler.line"] = "The city is quiet tonight. Your lamp looks lovely.",
        ["customer.photographer.name"] = "Midnight Photographer",
        ["customer.photographer.line"] = "Until the rain stops, I may as well stay a while.",
        ["customer.gamer.name"] = "All-Night Gamer",
        ["customer.gamer.line"] = "I need one more cup before this match ends.",
        ["customer.detective.name"] = "Sleepless Detective",
        ["customer.detective.line"] = "Make it hot. I still have clues to chase.",
        ["customer.singer.name"] = "Resident Singer",
        ["customer.singer.line"] = "One last cup before the final song.",
        ["customer.barista.name"] = "Neighbor Barista",
        ["customer.barista.line"] = "Taking a break from coffee tonight. Show me your new menu.",
        ["customer.student.name"] = "Thesis Student",
        ["customer.student.line"] = "Looks like an all-nighter. I need something lively.",
        ["customer.driver.name"] = "Night Driver",
        ["customer.driver.line"] = "A couple more routes to go. Make it a strong one.",
        ["customer.designer.name"] = "Freelance Designer",
        ["customer.designer.line"] = "I'm waiting for inspiration, and for the rain to stop.",
        ["customer.critic.name"] = "Late Food Critic",
        ["customer.critic.line"] = "I'd like to try something a little more refined tonight.",
        ["customer.streamer.name"] = "Post-Stream Host",
        ["customer.streamer.line"] = "The stream just ended. Give me something bright.",
        ["customer.collector.name"] = "Vintage Collector",
        ["customer.collector.line"] = "Your shop has more character every night. Make it warm.",
        ["customer.producer.name"] = "Record Producer",
        ["customer.producer.line"] = "The best mixes happen after midnight. Give me your most special drink.",
        ["decor.warm_lamp.name"] = "Warm Desk Lamp",
        ["decor.potted_plant.name"] = "Window Plant",
        ["decor.record_player.name"] = "Record Player",
        ["decor.curtain.name"] = "Rain Curtain",
        ["decor.shelf.name"] = "Tea Shelf",
        ["decor.lamp_banner.name"] = "Neon Sign",
        ["decor.wall_clock.name"] = "Old Wall Clock",
        ["decor.brass_kettle.name"] = "Brass Kettle Display",
        ["decor.postcard_wall.name"] = "Traveler Postcard Wall",
        ["decor.incense_set.name"] = "Incense Display",
        ["decor.tea_canister.name"] = "Tea Canister Set",
        ["decor.floor_lantern.name"] = "Floor Lantern",
        ["decor.ceramic_cups.name"] = "Ceramic Cup Set",
        ["decor.story_board.name"] = "Story Board",
        ["decor.rain_sign.name"] = "Rain Alley Neon",
        ["decor.vinyl_shelf.name"] = "Vinyl Shelf",
        ["decor.cat_clock.name"] = "Lucky Cat Clock",
        ["decor.herb_dryer.name"] = "Herb Dryer",
        ["decor.greenhouse_corner.name"] = "Mini Greenhouse Corner",
        ["decor.hanging_lights.name"] = "Hanging Lights",
        ["decor.premium_counter.name"] = "Brass Front Counter",
        ["decor.skylight.name"] = "Star Skylight",
        ["blessing.golden_spoon.name"] = "Golden Spoon",
        ["blessing.fragrant_steam.name"] = "Fragrant Steam",
        ["blessing.warm_counter.name"] = "Warm Counter",
        ["blessing.late_tip.name"] = "Late Tip",
        ["blessing.cash_box.name"] = "Cash Box",
        ["blessing.night_prep.name"] = "Night Prep",
        ["blessing.house_special.name"] = "House Special",
        ["blessing.quick_hand.name"] = "Quick Hands",
        ["blessing.warm_blend.name"] = "Warm Blend",
        ["blessing.flower_recipe.name"] = "Floral Recipe",
        ["blessing.cream_top.name"] = "Cream Top",
        ["blessing.cold_brew_note.name"] = "Cold Brew Notes",
        ["blessing.double_order.name"] = "Double Order",
        ["blessing.word_of_mouth.name"] = "Word of Mouth",
        ["blessing.rush_hour.name"] = "Rush Hour",
        ["blessing.story_whisper.name"] = "Old Town Whisper",
        ["blessing.silver_menu.name"] = "Silver Menu",
        ["blessing.second_wind.name"] = "Second Wind",
        ["blessing.chain_memory.name"] = "Chain Memory",
        ["blessing.tea_ritual.name"] = "Closing Ritual",
        ["blessing.spotlight_special.name"] = "Spotlight Special",
        ["blessing.soft_service.name"] = "Soft Service",
        ["blessing.flower_market.name"] = "Flower Market",
        ["blessing.milk_street.name"] = "Cream Street",
        ["blessing.fresh_route.name"] = "Fresh Route",
        ["blessing.warm_hearth.name"] = "Warm Hearth",
        ["blessing.reputation_echo.name"] = "Echoed Reputation",
        ["blessing.festival_board.name"] = "Festival Board",
    };

    public static GameLanguage Current { get; private set; } = GameLanguage.Chinese;
    public static string Code => Current == GameLanguage.Chinese ? "zh-CN" : "en";

    public static void Set(string? code)
    {
        Current = code != null && code.StartsWith("en") ? GameLanguage.English : GameLanguage.Chinese;
    }

    public static void Toggle()
    {
        Current = Current == GameLanguage.Chinese ? GameLanguage.English : GameLanguage.Chinese;
    }

    public static string Text(string key, string fallback = "")
    {
        var dict = Current == GameLanguage.Chinese ? Zh : En;
        return dict.TryGetValue(key, out var value) ? value : fallback;
    }

    public static string Format(string key, params object[] args)
    {
        return string.Format(Text(key, key), args);
    }

    public static string Content(string type, string id, string field, string fallback)
    {
        return Text($"{type}.{id}.{field}", fallback);
    }
}
